language: python
python:
- 3.6
install:
- pip install -Ur requirements-dev.txt
- pip install .
- pip install codecov
script:
- make cov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: terrycain
  password:
    secure: bX38Kb9hIpckv9X7uNvd3QgP/7GXYC5l7dYNR1B31pBq2s0dspdGBOIw3BsJLo9sXC5rDSjHzVFhz2hLHYUiFs+q+YOWdp9jOEPCTtUxovLosGA/5/l2FFRnt+JVsEefRTn34jGO5tfFP91ESKSL6Q82WsGv8HZaGkgcCMJVSNfaUb4R30VAhDQuEF15qw9X6igKhH48fK+QZVYs59CpWvdMMVhS5W5UPzrHe+odqdmXNQmSUbyOD/Y8TvOOa3LUnwXgYM1IlGBC6CCLavfSZ+dXI7sW2R4Th4niRLgBX9pCcKDnHxZO16FUGEihcNl6ffXFa8e2JSCm9X/0pXXiNprx/RWYOaIP6zTWeFLFFIfAS+4K9Xvbo5ZwIKyqITA3YEjaIoW1KxWxyodm5pqi2FwS4HhLjPwRSTPVt/Xem5rZySyEURSeZpWsDU8RleYerDAYuruCwnF0W8HHdfR8ASMoSjAV0VkTkqtjHxwxUP8yRg3Q/8TiootNq3gQUhW7nt4YPZwtbU0DeP1Vpdhmi/6BYZSLTlhkG5sPKGMyMIHex6KFI9lgsXxJ5r1dOF5ZbTBQmBiC24MNcEB6OF9+qlDGWCcqW1pSC6xwfTrCMxtvoog+qN9bLS2+6W/TzGySXF0D2/X8q/2hVLBB8pvliQcmO2KdR7NXg1JZpSxaxKs=
  on:
    python: 3.6
    repo: terrycain/sanic-json-logging
    tags: true
after_success:
- codecov
